# Starts optimism-integration L1 and L2 local chains and runs Optimism integration tests against them
# TODO: The Optimism ops tool is currently unstable, thue the commented out code below.
{{> job-header-machine.yml}}
# set custom delimiter to avoid checksum parsing
{{=<% %>=}}
resource_class: large
environment:
  OPTIMISM_TEST_COMMIT: '08d1c86a7878900cc70be59aee70e724e680ec9e'
steps:
  - checkout
  - attach_workspace:
      at: .
  - restore_cache:
      keys:
        - v6-optimism-build-${OPTIMISM_TEST_COMMIT}
  - run:
      name: Build docker containers if necessary
      command: |
        if [ ! -d ./optimism ]; then
          npx hardhat ops --fresh --build --build-ops --optimism-commit $OPTIMISM_TEST_COMMIT
        fi;
  - save_cache:
      key: v6-optimism-build-{{ checksum "package-lock.json" }}
      paths:
        - ./optimism
  - run:
      name: Start docker chains
      background: true
      command: |
        docker --version
        npx hardhat ops --start --optimism-commit $OPTIMISM_TEST_COMMIT
  - cmd-wait-for-port:
      port: 8545
  - cmd-wait-for-port:
      port: 9545
  - run:
      name: Run isolated layer 1 integration tests
      command: |
        npx hardhat test:integration:l1 --compile --deploy --provider-port 9545
  - run:
      name: Run isolated layer 2 integration tests
      command: |
        npx hardhat test:integration:l2 --compile --deploy
  - run:
      name: Run dual layer 1 and layer 2 integration tests
      command: |
        npx hardhat test:integration:dual --deploy
