# Measures deployment and transaction gas usage in unit tests
working_directory: ~/repo
docker:
  - image: synthetixio/docker-node:14.16-focal
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Upload gas reports
      command: |
        npm --version
        npx hardhat test:merge-gas-reports gasReporterOutput-*.json
        npx codechecks codechecks.unit.yml
  - store_artifacts:
      path: gasReporterOutput.json
