# Measures deployment and transaction gas usage in unit tests
{{> job-header-sec-tools.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Upload gas reports
      command: |
        npx hardhat test:merge-gas-reports gasReporterOutput-*.json
        # required for codechecks
        git branch -f master origin/master
        codechecks codechecks.unit.yml
  - store_artifacts:
      path: gasReporterOutput.json
