# Measures unit and spec test coverage
{{> job-header-sec-tools.yml}}
steps:
  - checkout
  - attach_workspace:
      at: /tmp/coverage
  - run:
      name: Upload coverage
      command: |
        cp -R /tmp/coverage/coverage-*.json .
        bash <(curl -s https://codecov.io/bash)
