# Measures deployment and transaction gas usage in unit tests
{{> job-header-node.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Upload gas reports
      command: |
        npx hardhat test:merge-gas-reports gasReporterOutput-*.json
        npx codechecks codechecks.unit.yml
  - store_artifacts:
      path: gasReporterOutput.json
